// ----------------------------------------------------------------------

export const role = [
  'quản lý',
  'quản lý',
  'nhân viên',
  'quản lý',
  'quản lý',
  'nhân viên lâu năm',
  'leader',
  'nhân viên',
  'nhân viên lâu năm',
  'ui designer',
  'ui/quản lý',
  'ui/quản lý',
  'ui designer',
  'nhân viên',
  'nhân viên',
  'front end developer',
  'nhân viên',
  'quản lý',
  'full stack developer',
  'nhân viên',
  'quản lý',
  'ui designer',
  'nhân viên lâu năm',
  'ui/quản lý',
  'ui designer',
  'nhân viên lâu năm',
  'full stack developer',
  'hr manager',
  'hr manager',
  'ui/quản lý',
  'nhân viên lâu năm',
  'quản lý',
  'ui designer',
  'leader',
  'front end developer',
  'ui/quản lý',
  'nhân viên lâu năm',
  'ui/quản lý',
  'ui designer',
  'quản lý',
];
